### ISSUE TITLE
`add_null_constraint` fails with undefined method `match?' for /^".*"$/:Regexp

### ISSUE THREAD

**Issue by brightbytes-dude** [nullobject/rein#45]
With ActiveRecord 4.2.10, when running this line in a migration:

```
    add_null_constraint :ews_students, :first_name, if: "last_name IS NULL"
```

... the following occurs:

```
undefined method `match?' for /^".*"$/:Regexp
Did you mean?  match
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rein-3.5.0/lib/rein/util.rb:17:in `wrap_identifier'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rein-3.5.0/lib/rein/constraint/null.rb:27:in `_add_null_constraint'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rein-3.5.0/lib/rein/constraint/null.rb:11:in `block (2 levels) in add_null_constraint'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:511:in `up'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rein-3.5.0/lib/rein/constraint/null.rb:11:in `block in add_null_constraint'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:547:in `block in reversible'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:746:in `execute_block'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:547:in `reversible'
/Users/aaron/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rein-3.5.0/lib/rein/constraint/null.rb:10:in `add_null_constraint'
/Users/aaron/git/clarity_early_warning/db/migrate/20180920222205_nullable_first_name.rb:5:in `up'
```

**Comment by sasinda** [comment]
having the same issue with add_inclusion_constraint
